### ISSUE TITLE
企業アイコン・文字などの削減

### ISSUE THREAD

**Issue by cooltiger** [cooltiger/tokex#3]
- 文言：「Longhash」→「Tokex」へ変更
- アイコン：「LONGHASH」→「TOKEX」へ変更。（素材が無い場合、相談してください。）
- リンク：　Meetup 削除
- リンク：　EN|日本語、twitter、facebook、とりあえず非表示
- Mediaのブロックを非表示。

**Comment by Hiromu88** [comment]
終了
