### ISSUE TITLE
ヘッダーとフッター

### ISSUE THREAD

**Issue by cooltiger** [cooltiger/tokex#5]
- twitter、facebookアカウントがまだないので、取りあえずコメントアウトします。
- フッターに「© 2018 LONGHASH. All rights reserved.」
　を「© 2018 Tokex. All rights reserved.」へ変更する。

**Comment by Hiromu88** [comment]
witter、facebookアカウントがまだないので、取りあえずコメントアウトします。
→終了

**Comment by cooltiger** [comment]
- [x]    フッターに「©2018 LONGHASH. All rights reserved.」
　を「© 2018 Tokex. All rights reserved.」へ変更する。
